# Generated by Django 4.0.3 on 2022-03-05 06:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='relations.Contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
