# Generated by Django 4.0.3 on 2022-03-06 09:07

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('url', models.URLField()),
                ('image', models.ImageField(upload_to='images/bookmark/%Y/%m/%d/')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='متن')),
                ('created', models.DateField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_created', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('users_like', models.ManyToManyField(blank=True, related_name='image_liked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'بوکمارک',
                'verbose_name_plural': 'بوکمارک ها ',
                'ordering': ('-created',),
            },
        ),
    ]
