# Generated by Django 4.0.3 on 2022-03-15 21:21

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='عنوان')),
                ('cover', models.ImageField(upload_to='images/category/%Y/%m/%d/')),
                ('slug', models.SlugField(default='', max_length=100, unique=True, verbose_name='لينك')),
                ('status', models.BooleanField(default=True, verbose_name='نمايش داده شود ؟')),
                ('description', models.CharField(default='', max_length=512, verbose_name='توضيحات')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='blog.category', verbose_name='زیر دسته')),
            ],
            options={
                'verbose_name': 'دسته بندي',
                'verbose_name_plural': 'دسته بندي ها',
                'ordering': ['parent__id'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='عنوان')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='متن')),
                ('cover', models.ImageField(upload_to='images/article/%Y/%m/%d/')),
                ('promote', models.BooleanField(default=False)),
                ('slug', models.SlugField(default='', max_length=100, unique=True, verbose_name='لينك')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ ساخت')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ تغيير')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ انتشار')),
                ('status', models.CharField(choices=[('P', 'Published'), ('D', 'Draft')], default='d', max_length=1, verbose_name='وضعيت')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='نويسنده')),
                ('category', models.ManyToManyField(related_name='articles', to='blog.category', verbose_name='دسته بندي')),
                ('users_like', models.ManyToManyField(blank=True, related_name='article_liked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ('-publish',),
            },
        ),
    ]
