# Generated by Django 4.0.3 on 2022-03-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(upload_to='images/article/%Y/%m/%d/'),
        ),
    ]
